/*
 * System call argument map header.
 *
 * DO NOT EDIT-- this file is automatically generated.
 * $FreeBSD$
 * created from FreeBSD
 */

#ifndef _CHERIABI_SYSARGMAP_H_
#define	_CHERIABI_SYSARGMAP_H_

#include <sys/types.h>
#include <compat/cheriabi/cheriabi_syscall.h>

struct CHERIABI_SYS_sam {
	u_char sam_return_ptr;
	u_char sam_ptrmask;
};

extern struct CHERIABI_SYS_sam CHERIABI_SYS_argmap[CHERIABI_SYS_MAXSYSCALL];
#endif /* !_CHERIABI_SYSARGMAP_H_ */
